In [1]:
import torch
import numpy as np


In [2]:
np_y = np.ones([5,3])

In [3]:
np_y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
ts_y = torch.tensor(np_y)

In [6]:
print(ts_y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
data = [1,2,3]

ts_data = torch.tensor(data, dtype=torch.float64)


In [8]:
print(ts_data)

tensor([1., 2., 3.], dtype=torch.float64)


In [9]:
data = [[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]]


In [10]:
ts_data = torch.tensor(data)

In [11]:
ts_data.size()

torch.Size([2, 2, 3])

In [12]:
ts_data = torch.tensor([[1, 2, 3],[4, 5, 6]])
ts_data1 = torch.tensor([[10, 20, 30],[40, 50, 60]]) 


In [13]:
ts_x = ts_data - ts_data1

In [14]:
ts_x

tensor([[ -9, -18, -27],
        [-36, -45, -54]])

In [15]:
ts_sample = torch.tensor([[1,2,3],[-4,-5,-6]],dtype=float)


In [16]:
print(torch.abs(ts_sample))

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


In [17]:
print(torch.std(ts_sample))

tensor(3.9370, dtype=torch.float64)
