In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
gen = np.random.RandomState(0)

In [3]:
a1 = gen.randn(4,4)
a2 = gen.randn(4,4)
a3 = gen.randn(4)

In [7]:
a4 = np.hstack((a1, a2))

In [9]:
str(a4)

'[[ 1.76405235  0.40015721  0.97873798  2.2408932   1.49407907 -0.20515826\n   0.3130677  -0.85409574]\n [ 1.86755799 -0.97727788  0.95008842 -0.15135721 -2.55298982  0.6536186\n   0.8644362  -0.74216502]\n [-0.10321885  0.4105985   0.14404357  1.45427351  2.26975462 -1.45436567\n   0.04575852 -0.18718385]\n [ 0.76103773  0.12167502  0.44386323  0.33367433  1.53277921  1.46935877\n   0.15494743  0.37816252]]'

In [11]:
a4.ndim

2

In [17]:
a5 = np.vstack((a1,a2))

In [13]:
a4

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.49407907,
        -0.20515826,  0.3130677 , -0.85409574],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721, -2.55298982,
         0.6536186 ,  0.8644362 , -0.74216502],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351,  2.26975462,
        -1.45436567,  0.04575852, -0.18718385],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433,  1.53277921,
         1.46935877,  0.15494743,  0.37816252]])

In [18]:
a6 = np.dstack(a1, a2)

2

In [24]:
a7 = np.row_stack((a1, a3))

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [-0.88778575, -1.98079647, -0.34791215,  0.15634897]])

In [16]:
a8 = np.column_stack((a1, a3))

2

In [19]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [20]:
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
np.arange(6).reshape(2,3).T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [40]:
a1 = np.arange(16).reshape(4,4)
a2 = np.arange(16,32).reshape(4,4)
a3 = np.arange(4)

In [41]:
a2

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [42]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [43]:
a3

array([0, 1, 2, 3])

In [44]:
np.column_stack((a1, a3))

array([[ 0,  1,  2,  3,  0],
       [ 4,  5,  6,  7,  1],
       [ 8,  9, 10, 11,  2],
       [12, 13, 14, 15,  3]])

In [45]:
np.row_stack((a1, a3))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3]])

In [46]:
gen.randn(4,4)

array([[-1.07075262,  1.05445173, -0.40317695,  1.22244507],
       [ 0.20827498,  0.97663904,  0.3563664 ,  0.70657317],
       [ 0.01050002,  1.78587049,  0.12691209,  0.40198936],
       [ 1.8831507 , -1.34775906, -1.270485  ,  0.96939671]])

In [47]:
np.column_stack((a1, a3))

array([[ 0,  1,  2,  3,  0],
       [ 4,  5,  6,  7,  1],
       [ 8,  9, 10, 11,  2],
       [12, 13, 14, 15,  3]])

In [48]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
a1.mean()

7.5

In [50]:
a1.mean(axis=1)

array([ 1.5,  5.5,  9.5, 13.5])

In [51]:
a1.mean(axis=0)

array([6., 7., 8., 9.])

In [52]:
a2.cumprod(axis=1)

array([[    16,    272,   4896,  93024],
       [    20,    420,   9240, 212520],
       [    24,    600,  15600, 421200],
       [    28,    812,  24360, 755160]])

In [53]:
a1.std(axis=0)

array([4.47213595, 4.47213595, 4.47213595, 4.47213595])

In [4]:
a1.argmin(axis=0)

array([2, 1, 2, 1])

In [5]:
gen = np.random.RandomState(0)

In [6]:
a1 = gen.randn(8,8)

In [9]:
a1.shape

(8, 8)

In [10]:
res1 = a1.mean()

In [11]:
res2 = a1.std(axis=1)

In [12]:
a = np.array([[1,2,3],[4,5,6]])

In [13]:
a.mean()

3.5

In [14]:
a.shape

(2, 3)

In [15]:
a.mean(axis=1)

array([2., 5.])

In [16]:
a.mean(axis=0)

array([2.5, 3.5, 4.5])

In [26]:
a.max(axis=0).argmax()

2

In [23]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
a2.min(axis=1)

array([-0.85409574, -2.55298982, -1.45436567,  0.15494743])

In [28]:
a.min(axis=1)

array([1, 4])

In [29]:
a.max(axis=1)

array([3, 6])

In [30]:
a.argmax()

5

In [31]:
a.argmax(axis=1)

array([2, 2])

In [32]:
a.min(axis=1).argmin()

0

In [34]:
a.min(axis=1).argmin()

0